import java.awt.*;
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
public class MovieCashier extends javax.swing.JFrame {

    /**
     * Creates new form MovieCashier
     */
    public MovieCashier() {
        initComponents();
        Image();
    }
    
    public void Image() {
        ImageIcon icon = new ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\FinalProject\\src\\main\\java\\Images\\movie1.jpg");
        Image scaledIcon = icon.getImage().getScaledInstance(200, 300, Image.SCALE_SMOOTH);

        movie1Button.setText("ShowTimes");
        movie1Button.setIcon(new ImageIcon(scaledIcon));

    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        movie1Button = new javax.swing.JButton();
        movie1Button1 = new javax.swing.JButton();
        movie1Button2 = new javax.swing.JButton();
        movie1Button3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MovieCashier");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 50)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ABREEZA CINEMA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 70));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("A Smart Movie Ticketing System");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 15, 510, 40));

        movie1Button.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        movie1Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        movie1Button.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        movie1Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(movie1Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 200, 220, 530));

        movie1Button1.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        movie1Button1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        movie1Button1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(movie1Button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 220, 530));

        movie1Button2.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        movie1Button2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        movie1Button2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(movie1Button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 220, 530));

        movie1Button3.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        movie1Button3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        movie1Button3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(movie1Button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 220, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieCashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieCashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieCashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieCashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieCashier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton movie1Button;
    private javax.swing.JButton movie1Button1;
    private javax.swing.JButton movie1Button2;
    private javax.swing.JButton movie1Button3;
    // End of variables declaration//GEN-END:variables
}
